Change "filename" string to "files" list
repo-helper/hatch-requirements-txt pull request #13
Opened 2022-09-20 22:45 UTC by maresb

Implements the second suggestion in #6

2022-09-21 19:11 UTC, domdfcoding reviewed
I'm happy with the main code changes, but I haven't had a chance to look at the tests yet.

2022-09-21 19:11 UTC, domdfcoding commented on hatch_requirements_txt/__init__.py
> +		raise ValueError(f"Requirements files must be a list, but got {type(files)}: {files}.")
I feel like this (and the one a few lines down) should be `TypeError` instead, as the issue is that the *type* is wrong.

2022-09-21 20:24 UTC, maresb commented on hatch_requirements_txt/__init__.py
> +		raise ValueError(f"Requirements files must be a list, but got {type(files)}: {files}.")
Yes, good call. Fixed.

2022-10-01 21:52 UTC, maresb commented
@domdfcoding I didn't realize that the coverage tests were failing. (I don't think I got notified when repo-helper added the tags.)

I added a few more tests. Could you please restart the CI?

2022-10-01 22:16 UTC, maresb commented
The flake8 failure looks like it may be caused by a discrepancy between the settings for `formate` and `flake8`.

2022-10-02 06:20 UTC, domdfcoding commented on tests/test_metadata.py
> +				pyproject_toml: str) -> Union[pkginfo.SDist, pkginfo.Wheel]:
```suggestion
def get_pkginfo(
		tmp_pathplus: PathPlus,
		build_func: Callable,
		pyproject_toml: str,
		) -> Union[pkginfo.SDist, pkginfo.Wheel]: 
```

That should make both formate and flake8 happy.

2022-10-02 08:35 UTC, maresb commented
Cool, thanks! Hopefully now the CI passes.

2022-10-02 13:54 UTC, ofek approved these changes

2022-10-04 10:36 UTC, domdfcoding requested changes

2022-10-04 10:36 UTC, domdfcoding commented on tests/test_metadata.py
> +			]
Could you also add a test where the optional requirements files are in a subdirectory? I've seen some projects that have it like:

```
requirements/dev.txt
requirements/docs.txt
requirements/tests.txt
```

Looking at the code it should work but it's worth testing.

2022-10-04 10:41 UTC, maresb commented on tests/test_metadata.py
> +			]
Ya, I'll try to do that this evening.

2022-10-04 18:43 UTC, maresb commented on tests/test_metadata.py
> +			]
@domdfcoding, I have added the requested test.

2022-10-05 21:40 UTC, ofek approved these changes

2022-10-07 13:23 UTC, merged

2022-10-07 18:24 UTC, maresb commented
Thanks @domdfcoding for the thorough review! I'm looking forward to the next release.